// Code generated by ferrum. DO NOT EDIT.
use rppal::gpio::Gpio;

pub fn blink_gpio() -> Gpio {
    // vord:hole iot-blink-gpio
    // ⛳ AI_FILL[iot_gpio] --context=iot:blink
    Gpio::new().unwrap()
    // vord:end-hole
}
