// Code generated by ferrum. DO NOT EDIT.
use ethercat_rs::Master;

pub fn robot_master() -> Master {
    // vord:hole iot-robot-ethercat
    // ⛳ AI_FILL[iot_ethercat] --context=iot:robot
    // TODO: replace with actual master discovery
    Master::default()
    // vord:end-hole
}
