// Code generated by ferrum. DO NOT EDIT.
use rumqttc::{MqttOptions, Client};

pub fn telem_mqtt_client() -> Client {
    let options = MqttOptions::new("telem", "localhost", 1883);
    // vord:hole iot-telem-mqtt-client
    // ⛳ AI_FILL[iot_mqtt_client] --context=iot:telem
    Client::new(options, 10)
    // vord:end-hole
}
