use anyhow::Result;
use std::collections::BTreeMap;
use std::path::Path;
use ferrum_shared_models::{DslAuth, DslJob, DslResource, DslRoute, FerrumDsl};

/// Small filesystem helpers shared by plugin `init`/`compile` steps: writing
/// a scaffold file only if the user hasn't already customized it, and
/// idempotently declaring a crate dependency the plugin needs.
pub mod utils {
    use anyhow::Result;
    use std::fs;
    use std::path::Path;

    /// Write `content` to `path` unless something is already there.
    ///
    /// Plugin `init` steps run after the base scaffold, so a file may
    /// already have been generated (or hand-edited) by the time a plugin
    /// wants to drop in its own version; overwriting it would silently
    /// discard that.
    pub fn copy_if_missing(content: &str, path: &Path) -> Result<()> {
        if path.exists() {
            return Ok(());
        }
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, content)?;
        Ok(())
    }

    /// Idempotently declare `name = "version"` in `backend/Cargo.toml`'s
    /// dependency table, relative to the current directory.
    ///
    /// This is a plain text append rather than a TOML-aware edit: plugin
    /// `Cargo.toml` edits only ever add a bare `name = "version"` line, and
    /// keeping this dependency-free of a TOML crate keeps the engine crate
    /// light. Callers that need structured edits (features, tables) should
    /// go through `toml::Value` themselves, as `ferrum-cli`'s `init` does.
    pub fn ensure_dep(name: &str, version: &str) -> Result<()> {
        let path = Path::new("backend/Cargo.toml");
        let mut content = fs::read_to_string(path)?;
        if content.contains(name) {
            return Ok(());
        }
        if !content.ends_with('\n') {
            content.push('\n');
        }
        content.push_str(&format!("{name} = \"{version}\"\n"));
        fs::write(path, content)?;
        Ok(())
    }
}

pub struct PluginMetadata {
    pub library: String,
}

impl PluginMetadata {
    /// Placeholder for loading a third-party plugin's `plugin.toml`.
    ///
    /// Dynamic (compiled-elsewhere) plugin loading isn't implemented yet —
    /// there's no defined ABI for calling into a `cdylib` loaded at
    /// runtime — so this never reads `_path`. It exists so `add_plugin`'s
    /// SHA256-of-the-built-library step has something to call; it always
    /// resolves to a library path that doesn't exist, so that step is
    /// effectively a no-op until real dynamic loading is built.
    pub fn from_file(_path: &Path) -> Result<Self> {
        Ok(PluginMetadata {
            library: " ".to_string(),
        })
    }
}

pub struct DynamicPlugin;

impl DynamicPlugin {
    /// Placeholder for loading a third-party plugin's compiled library.
    /// See [`PluginMetadata::from_file`] — same gap, not yet implemented.
    pub fn load(_path: &Path) -> Result<Self> {
        Ok(DynamicPlugin)
    }
}

impl Plugin for DynamicPlugin {}

/// A built-in "battery": a known capability `ferrum add-plugin <name>`
/// can register, which [`PluginManager::extend_dsl_all`] then applies to
/// the parsed DSL before code generation.
pub trait Plugin {
    /// Add this plugin's routes/resources/jobs/features to the DSL.
    fn extend_dsl(&self, _dsl: &mut FerrumDsl) -> Result<()> {
        Ok(())
    }

    /// Run after code generation (e.g. write a file the generator doesn't
    /// know how to template).
    fn compile(&self) -> Result<()> {
        Ok(())
    }

    /// Run once, right after `ferrum init`.
    fn init(&self) -> Result<()> {
        Ok(())
    }
}

fn push_feature(dsl: &mut FerrumDsl, name: &str) {
    if !dsl.app.features.iter().any(|f| f == name) {
        dsl.app.features.push(name.to_string());
    }
}

pub struct GraphQLPlugin;

impl Plugin for GraphQLPlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "graphql");
        Ok(())
    }

    fn compile(&self) -> Result<()> {
        utils::copy_if_missing(
            "// Generated by the graphql plugin. Fill in your schema here.\n",
            Path::new("backend/src/graphql_schema.rs"),
        )
    }
}

pub struct AuthPlugin;

impl Plugin for AuthPlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "auth");
        if dsl.app.auth.is_none() {
            dsl.app.auth = Some(DslAuth {
                user_entity: "User".to_string(),
                methods: vec!["password".to_string()],
                on_auth_failed_redirect_to: None,
            });
        }
        Ok(())
    }
}

pub struct AuthPasswordPlugin;

impl Plugin for AuthPasswordPlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "auth-password");
        if dsl.app.auth.is_none() {
            dsl.app.auth = Some(DslAuth {
                user_entity: "User".to_string(),
                methods: vec!["password".to_string()],
                on_auth_failed_redirect_to: None,
            });
        }
        Ok(())
    }
}

pub struct AuthOAuthPlugin;

impl Plugin for AuthOAuthPlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "auth-oauth");
        if dsl.app.auth.is_none() {
            dsl.app.auth = Some(DslAuth {
                user_entity: "User".to_string(),
                methods: vec!["oauth".to_string()],
                on_auth_failed_redirect_to: None,
            });
        }
        Ok(())
    }
}

pub struct StripePlugin;

impl Plugin for StripePlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "stripe");
        dsl.resources.push(DslResource {
            name: "StripeClient".to_string(),
            resource_type: "stripe".to_string(),
            config: BTreeMap::new(),
        });
        dsl.routes.push(DslRoute {
            name: "stripeWebhook".to_string(),
            path: "/webhooks/stripe".to_string(),
            to: "stripe.webhook".to_string(),
            auth_required: false,
            policy: None,
        });
        Ok(())
    }
}

pub struct CronPlugin;

impl Plugin for CronPlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "cron");
        dsl.jobs.push(DslJob {
            name: "example_job".to_string(),
            schedule: "0 0 * * *".to_string(),
            handler: "cron.example_job".to_string(),
            policy: None,
        });
        Ok(())
    }
}

pub struct CmsSanityPlugin;

impl Plugin for CmsSanityPlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "cms-sanity");
        dsl.resources.push(DslResource {
            name: "SanityClient".to_string(),
            resource_type: "cms-sanity".to_string(),
            config: BTreeMap::new(),
        });
        Ok(())
    }
}

pub struct CmsNotionPlugin;

impl Plugin for CmsNotionPlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "cms-notion");
        dsl.resources.push(DslResource {
            name: "NotionClient".to_string(),
            resource_type: "cms-notion".to_string(),
            config: BTreeMap::new(),
        });
        Ok(())
    }
}

pub struct RealtimeSsePlugin;

impl Plugin for RealtimeSsePlugin {
    fn extend_dsl(&self, dsl: &mut FerrumDsl) -> Result<()> {
        push_feature(dsl, "realtime-sse");
        Ok(())
    }
}

#[derive(Default)]
pub struct PluginManager {
    plugins: Vec<Box<dyn Plugin>>,
}

impl PluginManager {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn register<T: Plugin + 'static>(&mut self, plugin: T) {
        self.plugins.push(Box::new(plugin));
    }

    pub fn compile_all(&self) -> Result<()> {
        for plugin in &self.plugins {
            plugin.compile()?;
        }
        Ok(())
    }

    pub fn extend_dsl_all(&self, dsl: &mut FerrumDsl) -> Result<()> {
        for plugin in &self.plugins {
            plugin.extend_dsl(dsl)?;
        }
        Ok(())
    }

    pub fn init_all(&self) -> Result<()> {
        for plugin in &self.plugins {
            plugin.init()?;
        }
        Ok(())
    }
}
