"""
Tests for Langflow workflow versioning.

This module contains tests for the Langflow workflow versioning implementation,
verifying proper export and version control integration.
"""

import unittest
from unittest.mock import MagicMock, patch
import json
import os
import tempfile
import shutil
import subprocess
from datetime import datetime

from ui_adapters.langflow.workflow_versioning import WorkflowVersionManager


class TestWorkflowVersioning(unittest.TestCase):
    """Test suite for Langflow workflow versioning."""

    def setUp(self):
        """Set up test environment."""
        # Create temporary directory for workflow storage
        self.temp_dir = tempfile.mkdtemp()

        # Create version manager with Git disabled for most tests
        self.version_manager = WorkflowVersionManager(
            storage_dir=self.temp_dir,
            git_enabled=False,
            max_versions=5
        )

        # Create sample workflow data
        self.workflow_id = "test_workflow"
        self.workflow_data = {
            "id": self.workflow_id,
            "steps": [
                {"type": "graphrag_query", "question": "What is GraphRAG?"},
                {"type": "graphrag_index", "docs": ["Test document"]}
            ]
        }

    def tearDown(self):
        """Clean up test environment."""
        # Remove temporary directory
        shutil.rmtree(self.temp_dir)

    def test_save_workflow(self):
        """Test workflow saving."""
        # Call method under test
        result = self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=self.workflow_data
        )

        # Verify results
        self.assertEqual(result["workflow_id"], self.workflow_id)
        self.assertIn("version_id", result)
        self.assertIn("saved_at", result)

        # Verify files were created
        workflow_dir = os.path.join(self.temp_dir, self.workflow_id)
        self.assertTrue(os.path.exists(workflow_dir))
        self.assertTrue(os.path.exists(os.path.join(workflow_dir, "workflow.json")))
        self.assertTrue(os.path.exists(os.path.join(workflow_dir, "exports")))
        self.assertTrue(os.path.exists(os.path.join(workflow_dir, "exports", "workflow.py")))
        self.assertTrue(os.path.exists(os.path.join(workflow_dir, "exports", "workflow.ipynb")))
        self.assertTrue(os.path.exists(os.path.join(workflow_dir, "exports", "workflow.yaml")))
        self.assertTrue(os.path.exists(os.path.join(workflow_dir, "history.json")))

    def test_generate_version_id(self):
        """Test version ID generation."""
        # Call method under test
        version_id = self.version_manager._generate_version_id(self.workflow_data)

        # Verify results
        self.assertIsNotNone(version_id)
        self.assertGreater(len(version_id), 8)

        # Generate another version ID for the same workflow
        version_id2 = self.version_manager._generate_version_id(self.workflow_data)

        # Verify different version IDs for same content (due to timestamp)
        self.assertNotEqual(version_id, version_id2)

        # Modify workflow and check for different hash
        modified_workflow = self.workflow_data.copy()
        modified_workflow["steps"].append({"type": "custom_function", "function": "test"})

        version_id3 = self.version_manager._generate_version_id(modified_workflow)
        self.assertNotEqual(version_id2[-8:], version_id3[-8:])  # Hash part should differ

    def test_export_workflow_code(self):
        """Test workflow code export."""
        # Create workflow directory
        workflow_dir = os.path.join(self.temp_dir, self.workflow_id)
        os.makedirs(workflow_dir, exist_ok=True)

        # Call method under test
        self.version_manager._export_workflow_code(workflow_dir, self.workflow_data)

        # Verify exports were created
        exports_dir = os.path.join(workflow_dir, "exports")
        self.assertTrue(os.path.exists(exports_dir))
        self.assertTrue(os.path.exists(os.path.join(exports_dir, "workflow.py")))
        self.assertTrue(os.path.exists(os.path.join(exports_dir, "workflow.ipynb")))
        self.assertTrue(os.path.exists(os.path.join(exports_dir, "workflow.yaml")))

        # Verify Python code content
        with open(os.path.join(exports_dir, "workflow.py"), "r") as f:
            python_code = f.read()
            self.assertIn("# Generated by GraphRAG Ontology Application", python_code)
            self.assertIn(f"\"id\": \"{self.workflow_id}\"", python_code)
            self.assertIn("def execute_workflow(input_data):", python_code)

        # Verify notebook content
        with open(os.path.join(exports_dir, "workflow.ipynb"), "r") as f:
            notebook_json = json.load(f)
            self.assertIn("cells", notebook_json)
            self.assertIn("metadata", notebook_json)
            self.assertEqual(notebook_json["nbformat"], 4)

    def test_update_version_history(self):
        """Test version history updating."""
        # Call method under test
        history = self.version_manager._update_version_history(
            workflow_id=self.workflow_id,
            version_id="test_version",
            workflow_data=self.workflow_data
        )

        # Verify results
        self.assertEqual(len(history), 1)
        self.assertEqual(history[0]["version_id"], "test_version")
        self.assertEqual(history[0]["step_count"], 2)

        # Add more versions to test max_versions limit
        for i in range(10):
            history = self.version_manager._update_version_history(
                workflow_id=self.workflow_id,
                version_id=f"version_{i}",
                workflow_data=self.workflow_data
            )

        # Verify history was limited to max_versions
        self.assertEqual(len(history), 5)  # max_versions=5 in setUp
        self.assertEqual(history[-1]["version_id"], "version_9")

    def test_get_workflow_versions(self):
        """Test retrieving workflow versions."""
        # Save workflow to create version history
        self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=self.workflow_data
        )

        # Modify workflow and save again
        modified_workflow = self.workflow_data.copy()
        modified_workflow["steps"].append({"type": "custom_function", "function": "test"})

        self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=modified_workflow
        )

        # Call method under test
        versions = self.version_manager.get_workflow_versions(self.workflow_id)

        # Verify results
        self.assertEqual(len(versions), 2)
        self.assertEqual(versions[0]["step_count"], 3)  # Modified workflow has 3 steps
        self.assertEqual(versions[1]["step_count"], 2)  # Original workflow has 2 steps

    def test_get_workflow_version(self):
        """Test retrieving specific workflow version."""
        # Save workflow to create version
        result = self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=self.workflow_data
        )
        version_id = result["version_id"]

        # Call method under test
        workflow = self.version_manager.get_workflow_version(
            workflow_id=self.workflow_id,
            version_id=version_id
        )

        # Verify results
        self.assertEqual(workflow["id"], self.workflow_id)
        self.assertEqual(len(workflow["steps"]), 2)
        self.assertEqual(workflow["metadata"]["version_id"], version_id)

        # Test getting latest version
        latest_workflow = self.version_manager.get_workflow_version(
            workflow_id=self.workflow_id,
            version_id="latest"
        )

        self.assertEqual(latest_workflow["metadata"]["version_id"], version_id)

    def test_compare_workflow_versions(self):
        """Test comparing workflow versions."""
        # Save original workflow
        result1 = self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=self.workflow_data
        )
        version_id1 = result1["version_id"]

        # Modify workflow and save again
        modified_workflow = self.workflow_data.copy()
        modified_workflow["steps"].append({"type": "custom_function", "function": "test"})
        modified_workflow["steps"][0]["question"] = "What is GraphRAG technology?"

        result2 = self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=modified_workflow
        )
        version_id2 = result2["version_id"]

        # Call method under test
        comparison = self.version_manager.compare_workflow_versions(
            workflow_id=self.workflow_id,
            version_id1=version_id1,
            version_id2=version_id2
        )

        # Verify results
        self.assertEqual(comparison["workflow_id"], self.workflow_id)
        self.assertEqual(comparison["version1"], version_id1)
        self.assertEqual(comparison["version2"], version_id2)
        self.assertEqual(comparison["step_count1"], 2)
        self.assertEqual(comparison["step_count2"], 3)
        self.assertEqual(len(comparison["added_steps"]), 1)
        self.assertEqual(len(comparison["modified_steps"]), 1)
        self.assertEqual(len(comparison["removed_steps"]), 0)

    def test_revert_to_version(self):
        """Test reverting to previous version."""
        # Save original workflow
        result1 = self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=self.workflow_data
        )
        version_id1 = result1["version_id"]

        # Modify workflow and save again
        modified_workflow = self.workflow_data.copy()
        modified_workflow["steps"].append({"type": "custom_function", "function": "test"})

        self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=modified_workflow
        )

        # Call method under test
        revert_result = self.version_manager.revert_to_version(
            workflow_id=self.workflow_id,
            version_id=version_id1
        )

        # Verify results
        self.assertEqual(revert_result["workflow_id"], self.workflow_id)
        self.assertEqual(revert_result["original_version"], version_id1)
        self.assertEqual(revert_result["status"], "reverted")

        # Verify latest version is a revert
        latest_workflow = self.version_manager.get_workflow_version(
            workflow_id=self.workflow_id,
            version_id="latest"
        )

        self.assertEqual(len(latest_workflow["steps"]), 2)  # Original had 2 steps
        self.assertEqual(latest_workflow["metadata"]["author"], "revert_operation")

    def test_export_workflow(self):
        """Test exporting workflow as code."""
        # Save workflow
        self.version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=self.workflow_data
        )

        # Create output directory
        output_dir = os.path.join(self.temp_dir, "exports")
        os.makedirs(output_dir, exist_ok=True)

        # Call method under test for each format
        python_result = self.version_manager.export_workflow(
            workflow_id=self.workflow_id,
            format="python",
            output_dir=output_dir
        )

        notebook_result = self.version_manager.export_workflow(
            workflow_id=self.workflow_id,
            format="notebook",
            output_dir=output_dir
        )

        yaml_result = self.version_manager.export_workflow(
            workflow_id=self.workflow_id,
            format="yaml",
            output_dir=output_dir
        )

        # Verify results
        self.assertEqual(python_result["format"], "python")
        self.assertTrue(os.path.exists(python_result["output_path"]))
        self.assertTrue(python_result["output_path"].endswith(".py"))

        self.assertEqual(notebook_result["format"], "notebook")
        self.assertTrue(os.path.exists(notebook_result["output_path"]))
        self.assertTrue(notebook_result["output_path"].endswith(".ipynb"))

        self.assertEqual(yaml_result["format"], "yaml")
        self.assertTrue(os.path.exists(yaml_result["output_path"]))
        self.assertTrue(yaml_result["output_path"].endswith(".yaml"))

    @patch("subprocess.run")
    def test_git_integration(self, mock_run):
        """Test Git integration for version control."""
        # Configure mock to simulate Git availability
        mock_run.return_value.returncode = 0
        mock_run.return_value.stdout = "git version 2.30.0"

        # Create version manager with Git enabled
        git_version_manager = WorkflowVersionManager(
            storage_dir=self.temp_dir,
            git_enabled=True
        )

        # Verify Git initialization was attempted
        mock_run.assert_any_call(
            ["git", "--version"],
            capture_output=True,
            text=True,
            check=False
        )

        # Save workflow
        git_version_manager.save_workflow(
            workflow_id=self.workflow_id,
            workflow_data=self.workflow_data,
            commit_message="Initial commit"
        )

        # Verify Git commit was attempted
        mock_run.assert_any_call(
            ["git", "add", self.workflow_id],
            cwd=self.temp_dir,
            capture_output=True,
            text=True,
            check=False
        )

        # At least one call to git commit should have been made
        commit_calls = [call for call in mock_run.call_args_list if "commit" in str(call)]
        self.assertGreater(len(commit_calls), 0)


if __name__ == "__main__":
    unittest.main()