use ferrum_cli::commands::fill_todos_with_pattern;
use mockito::Server;
use serial_test::serial;
use std::fs;
use std::sync::{Mutex, OnceLock};
use tempfile::tempdir;

const TODO_PATTERN: &str = ferrum_compiler::AI_FILL_PATTERN;

static SERVER: OnceLock<Mutex<Server>> = OnceLock::new();

fn server() -> std::sync::MutexGuard<'static, Server> {
    SERVER
        .get_or_init(|| Mutex::new(Server::new_with_port(8001)))
        .lock()
        .unwrap()
}

#[test]
fn fill_todos_returns_err_on_invalid_regex() {
    let dir = tempdir().unwrap();
    let result = fill_todos_with_pattern(dir.path().to_path_buf(), "(");
    assert!(result.is_err());
}

#[test]
#[serial]
fn fill_todos_rewrites_marker() {
    let mut server = server();
    let _m = server
        .mock("POST", "/fill-todo")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{ "code": "fn filled() {}" }"#)
        .create();
    std::env::set_var("FERRUM_FILL_BASE", server.url());

    let dir = tempdir().unwrap();
    let file = dir.path().join("test.rs");
    fs::write(
        &file,
        "// \u{26F3} AI_FILL[do_it] --context=node",
    )
    .unwrap();

    fill_todos_with_pattern(dir.path().to_path_buf(), TODO_PATTERN).unwrap();
    std::env::remove_var("FERRUM_FILL_BASE");
    drop(server);

    let contents = fs::read_to_string(&file).unwrap();
    assert!(contents.contains("fn filled() {}"));
}

#[test]
#[serial]
fn fill_todos_fallback_on_empty_output() {
    let mut server = server();
    server
        .mock("POST", "/fill-todo")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{ "code": "" }"#)
        .create();

    server
        .mock("POST", "/fill-todo")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{ "code": "fn fallback() {}" }"#)
        .create();

    let _info = server.mock("POST", "/node-info").with_status(200).create();
    std::env::set_var("FERRUM_FILL_BASE", server.url());

    let dir = tempdir().unwrap();
    let file = dir.path().join("test.rs");
    fs::write(
        &file,
        "// \u{26F3} AI_FILL[do_it] --context=node",
    )
    .unwrap();

    std::env::set_var("FERRUM_TEST_INPUT", "extra info");
    fill_todos_with_pattern(dir.path().to_path_buf(), TODO_PATTERN).unwrap();
    std::env::remove_var("FERRUM_TEST_INPUT");
    std::env::remove_var("FERRUM_FILL_BASE");
    drop(server);

    let contents = fs::read_to_string(&file).unwrap();
    assert!(contents.contains("fn fallback() {}"));
}

#[test]
fn pattern_matches_canonical_and_legacy_markers() {
    let re = regex::Regex::new(TODO_PATTERN).unwrap();
    for marker in [
        "    // \u{26F3} AI_FILL[query_logic] --context=query:getPosts",
        "// \u{26F3}\u{FE0F} AI_FILL[job_logic] --context=job:cleanup",
        "    // \u{2699} AI_FILL[iot_rppal] --context=iot:rppal",
        "// \u{26F3}\u{FE0F} AI_FILL[task] --context NODE_ID",
    ] {
        let caps = re.captures(marker).unwrap_or_else(|| panic!("no match: {marker}"));
        assert!(!caps["task"].is_empty());
        assert!(!caps["context"].is_empty());
    }
}

/// Generated files keep AI_FILL inside a `vord:hole`; filling it must leave
/// the hole markers in place so the code survives recompiles.
#[test]
#[serial]
fn fill_todos_writes_inside_the_hole() {
    let mut server = server();
    let _m = server
        .mock("POST", "/fill-todo")
        .with_status(200)
        .with_header("content-type", "application/json")
        .with_body(r#"{ "code": "Json(vec![])" }"#)
        .create();
    std::env::set_var("FERRUM_FILL_BASE", server.url());

    let dir = tempdir().unwrap();
    let file = dir.path().join("get_posts.rs");
    fs::write(
        &file,
        "// Code generated by ferrum. DO NOT EDIT.\npub async fn get_posts() -> Json<Vec<Post>> {\n    // vord:hole query-get-posts\n    // \u{26F3} AI_FILL[query_logic] --context=query:getPosts\n    // vord:end-hole\n}\n",
    )
    .unwrap();

    fill_todos_with_pattern(dir.path().to_path_buf(), TODO_PATTERN).unwrap();
    std::env::remove_var("FERRUM_FILL_BASE");
    drop(server);

    let contents = fs::read_to_string(&file).unwrap();
    assert!(!contents.contains("AI_FILL"));
    let start = contents.find("// vord:hole query-get-posts").unwrap();
    let filled = contents.find("Json(vec![])").unwrap();
    let end = contents.find("// vord:end-hole").unwrap();
    assert!(start < filled && filled < end, "{contents}");
}
