//! Ownership markers on compiled output: generated-code headers, `vord:hole`
//! regions, AI_FILL markers and hole preservation across recompiles.

use ferrum_compiler::{
    compile_dsl, find_holes, has_generated_header, parse_dsl_yaml, project_to_modules,
    take_orphaned_holes, validate_features, validate_modules, validate_validations, Generator,
    ProjectPaths,
};
use std::fs;
use std::path::{Path, PathBuf};

const DSL: &str = r#"app:
  name: demo
  auth:
    userEntity: User
modules:
  users:
    entity:
      fields:
        email: string
    usecases:
      listUsers:
        input:
          limit: int
        output: User
      getUser:
        input:
          id: uuid
        output: User
routes:
  - name: home
    path: /
    to: HomePage
    authRequired: false
components:
  - name: UserCard
    props:
      - name: title
        type: string
queries:
  - name: getPosts
    handler: ./backend/queries/getPosts.rs
    entities: [Post]
mutations:
  - name: createUser
    handler: ./backend/mutations/create_user.rs
    entities: [User]
    policy: isAdmin
jobs:
  - name: nightlyCleanup
    schedule: "0 0 * * *"
    handler: nightly_cleanup
policies:
  - name: isAdmin
    guard: check_admin
  - name: isEditor
    guard: "role:editor"
iot:
  - name: blink
    code: |
      pub fn blink() {}
    protocol: gpio
    driver: rppal
    expose:
      method: POST
"#;

/// Files ferrum creates once and hands over: no header, no holes.
const USER_OWNED: &[&str] = &[
    "frontend/src/App.tsx",
    "frontend/src/pages/HomePage.tsx",
    "backend/src/db/mod.rs",
];

fn templates_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|apps| apps.parent())
        .expect("compiler crate sits at <root>/apps/compiler")
        .join("templates")
}

/// Run the same pipeline as `ferrum compile` for `yaml` into `out`.
fn compile(yaml: &str, out: &Path) {
    let dir = tempfile::tempdir().unwrap();
    let file = dir.path().join("grafo.yaml");
    fs::write(&file, yaml).unwrap();
    let mut dsl = parse_dsl_yaml(&file).unwrap();
    let modules = project_to_modules(&mut dsl).unwrap();
    validate_modules(&modules).unwrap();
    validate_features(&dsl, &modules).unwrap();
    validate_validations(&dsl, &modules).unwrap();
    let mut generator = Generator::new(templates_path().as_path(), out).unwrap();
    generator.set_modules(modules.clone());
    for m in &modules {
        generator.generate(m).unwrap();
    }
    compile_dsl(&dsl, &ProjectPaths::new(out)).unwrap();
}

fn all_files(root: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                stack.push(path);
            } else {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

fn rel(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap()
        .to_string_lossy()
        .replace('\\', "/")
}

fn read(path: &Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

#[test]
fn generated_files_carry_header_and_user_files_do_not() {
    let out = tempfile::tempdir().unwrap();
    compile(DSL, out.path());

    let mut headed = 0;
    for path in all_files(out.path()) {
        let name = rel(out.path(), &path);
        let content = read(&path);
        if USER_OWNED.contains(&name.as_str()) {
            assert!(!has_generated_header(&content), "{name} is user-owned");
            assert!(!content.contains("vord:hole"), "{name} is user-owned");
        } else if name.ends_with(".json") {
            // JSON has no comment syntax.
        } else {
            assert!(has_generated_header(&content), "{name} lacks the header");
            headed += 1;
        }
    }
    assert!(headed > 20, "only {headed} generated files");

    // The header is the first line, in the file's own comment syntax.
    let first = |p: &str| {
        read(&out.path().join(p))
            .lines()
            .next()
            .unwrap()
            .to_string()
    };
    assert_eq!(
        first("backend/mutations/create_user.rs"),
        "// Code generated by ferrum. DO NOT EDIT."
    );
    assert_eq!(
        first("frontend/src/routes.tsx"),
        "// Code generated by ferrum. DO NOT EDIT."
    );
    assert!(first("docs/policies.md").starts_with("<!-- Code generated by ferrum"));
    let migration = all_files(&out.path().join("backend/migrations"))
        .into_iter()
        .find(|p| p.ends_with("up.sql"))
        .unwrap();
    assert!(read(&migration).starts_with("-- Code generated by ferrum. DO NOT EDIT."));
    // Shared, region-assembled files are generated as a whole.
    assert!(has_generated_header(&read(
        &out.path().join("backend/src/db/models.rs")
    )));
}

#[test]
fn hand_written_logic_lives_in_named_holes() {
    let out = tempfile::tempdir().unwrap();
    compile(DSL, out.path());

    let expected = [
        ("backend/queries/get_posts.rs", "query-get-posts"),
        ("backend/mutations/create_user.rs", "mutation-create-user"),
        ("backend/jobs/nightly_cleanup.rs", "job-nightly-cleanup"),
        ("backend/handlers/users.rs", "usecase-list-users"),
        ("backend/policies/mod.rs", "policy-guards"),
        ("backend/auth.rs", "auth-login"),
        ("frontend/components/UserCard.tsx", "component-user-card"),
        ("backend/iot/blink_gpio.rs", "iot-blink-gpio"),
        ("backend/iot/blink_handler.rs", "iot-blink-http"),
    ];
    for (file, hole) in expected {
        let content = read(&out.path().join(file));
        assert!(
            has_generated_header(&content),
            "{file}: files with holes keep the header"
        );
        let lines: Vec<&str> = content.lines().collect();
        let holes = find_holes(&lines);
        assert!(
            holes.iter().any(|h| h.name == hole),
            "{file}: missing hole {hole}:\n{content}"
        );
        assert_eq!(
            content.matches("vord:hole ").count(),
            content.matches("vord:end-hole").count(),
            "{file}: unbalanced hole markers"
        );
    }

    // `role:` guards are generated; only custom guards need a hand-written body.
    let policies = read(&out.path().join("backend/policies/mod.rs"));
    assert!(policies.contains("pub fn check_admin() -> bool"));
    assert!(!policies.contains("fn editor"));
}

/// Every AI_FILL marker, in the output and in the templates, uses the one
/// canonical spelling and sits inside a hole; every hole has one.
#[test]
fn ai_fill_markers_are_canonical_and_inside_holes() {
    fn check(name: &str, content: &str) -> usize {
        let lines: Vec<&str> = content.lines().collect();
        let holes = find_holes(&lines);
        for (index, line) in lines.iter().enumerate() {
            if !line.contains("AI_FILL") {
                continue;
            }
            let marker = line.trim();
            assert!(
                marker.starts_with("// \u{26F3} AI_FILL[") && marker.contains("] --context="),
                "{name}:{}: non-canonical marker `{marker}`",
                index + 1
            );
            assert!(
                holes.iter().any(|h| h.body.contains(&index)),
                "{name}:{}: AI_FILL outside a hole",
                index + 1
            );
        }
        for hole in &holes {
            let markers = lines[hole.body.clone()]
                .iter()
                .filter(|l| l.contains("AI_FILL"))
                .count();
            assert_eq!(
                markers, 1,
                "{name}: hole {} needs one AI_FILL marker",
                hole.name
            );
        }
        holes.len()
    }

    let out = tempfile::tempdir().unwrap();
    compile(DSL, out.path());
    let mut holes = 0;
    for path in all_files(out.path()) {
        holes += check(&rel(out.path(), &path), &read(&path));
    }
    assert!(holes >= 9, "only {holes} holes in the output");

    let templates = templates_path();
    for path in all_files(&templates) {
        let name = rel(&templates, &path);
        if name.starts_with("semantic_gui/") {
            continue;
        }
        if let Ok(content) = fs::read_to_string(&path) {
            check(&name, &content);
        }
    }
}

#[test]
fn recompiling_keeps_hole_bodies() {
    let out = tempfile::tempdir().unwrap();
    compile(DSL, out.path());

    // Fill a hole and also tamper with generated code outside it.
    let edit = |file: &str, hole: &str, body: &str| {
        let path = out.path().join(file);
        let content = read(&path);
        let lines: Vec<&str> = content.lines().collect();
        let h = find_holes(&lines)
            .into_iter()
            .find(|h| h.name == hole)
            .unwrap();
        let mut edited: Vec<String> = lines[..h.body.start]
            .iter()
            .map(|l| l.to_string())
            .collect();
        edited.push(body.to_string());
        edited.extend(lines[h.body.end..].iter().map(|l| l.to_string()));
        fs::write(&path, edited.join("\n") + "\n").unwrap();
    };
    edit(
        "backend/mutations/create_user.rs",
        "mutation-create-user",
        "    let saved = save(_input);\n    Json(saved)",
    );
    // `users.rs` is rendered once per use case in a single compile, so the
    // hole has to survive an intermediate render that lacks it.
    edit(
        "backend/handlers/users.rs",
        "usecase-list-users",
        "    Ok(Json(load_one(&mut conn)))",
    );
    edit(
        "backend/policies/mod.rs",
        "policy-guards",
        "pub fn check_admin() -> bool { true }",
    );
    let mutation = out.path().join("backend/mutations/create_user.rs");
    let tampered = read(&mutation).replace("use crate::AppState;", "use crate::Hacked;");
    fs::write(&mutation, tampered).unwrap();

    compile(DSL, out.path());
    compile(DSL, out.path());

    let mutation = read(&mutation);
    assert!(
        mutation.contains("    let saved = save(_input);\n    Json(saved)\n    // vord:end-hole")
    );
    assert!(
        !mutation.contains("AI_FILL"),
        "the filled hole stays filled"
    );
    assert!(
        mutation.contains("use crate::AppState;"),
        "code outside holes is regenerated"
    );
    assert!(!mutation.contains("Hacked"));
    assert_eq!(
        mutation.matches("vord:hole mutation-create-user").count(),
        1
    );

    let handler = read(&out.path().join("backend/handlers/users.rs"));
    assert!(
        handler.contains("Ok(Json(load_one(&mut conn)))"),
        "{handler}"
    );

    let policies = read(&out.path().join("backend/policies/mod.rs"));
    assert!(policies.contains("pub fn check_admin() -> bool { true }"));

    // Nothing hand-written lost its hole, so nothing is reported.
    let lost: Vec<_> = take_orphaned_holes(out.path());
    assert!(lost.is_empty(), "{lost:?}");
}

#[test]
fn edited_hole_without_a_home_is_reported() {
    let out = tempfile::tempdir().unwrap();
    let file = out.path().join("thing.rs");
    ferrum_compiler::write_generated(&file, "// vord:hole old-name\n// x\n// vord:end-hole\n")
        .unwrap();
    let edited = read(&file).replace("// x", "mine();");
    fs::write(&file, edited).unwrap();

    ferrum_compiler::write_generated(&file, "// vord:hole new-name\n// y\n// vord:end-hole\n")
        .unwrap();

    let lost: Vec<_> = take_orphaned_holes(out.path());
    assert_eq!(lost, vec![(file.clone(), "old-name".to_string())]);
    assert!(read(&file).contains("// y"));
}
