#!/usr/bin/env python3
"""Generate `grafo.yaml` DSL fixtures for benchmarking the ferrum compiler.

Emits plain YAML text (no PyYAML dependency) so the fixtures are reproducible
and diffable. Three fixture families are produced:

  * tier<N>.yaml   -- new-style DSL, sized for scaling benchmarks
  * atlas.yaml     -- the flagship "complex app" (all DSL sections populated)
  * legacy_graph.yaml -- legacy raw `module:`/`nodes:` graph (ports/adapters)
  * collide.yaml   -- one module with many usecases (file-collision probe)
"""

from __future__ import annotations

import argparse
import os
from typing import Dict, List, Tuple

# --------------------------------------------------------------------------
# Domain vocabulary
# --------------------------------------------------------------------------

# 40 realistic bounded contexts. base[0] must stay "user": the `auth` feature
# requires an entity node with id == "user".
BASE_DOMAINS: List[str] = [
    "user", "tenant", "catalog", "inventory", "cart", "order", "payment",
    "shipment", "invoice", "analytics", "notification", "support", "pricing",
    "promotion", "review", "wishlist", "supplier", "warehouse", "return",
    "subscription", "loyalty", "tax", "currency", "address", "coupon",
    "campaign", "segment", "recommendation", "search", "content", "media",
    "translation", "audit", "webhook", "integration", "report", "dashboard",
    "workflow", "sla", "fraud",
]

ENTITY_FIELDS: List[Tuple[str, str]] = [
    ("name", "string"),
    ("code", "string"),
    ("status", "string"),
    ("quantity", "int"),
    ("amount", "float"),
    ("active", "bool"),
    ("tenantId", "uuid"),
    ("createdAt", "timestamp"),
]

UC_INPUT_POOL: List[Tuple[str, str]] = [
    ("id", "uuid"),
    ("tenantId", "uuid"),
    ("query", "string"),
    ("email", "string"),
    ("limit", "int"),
    ("offset", "int"),
    ("amount", "float"),
]


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def domain_name(index: int) -> str:
    if index < len(BASE_DOMAINS):
        return BASE_DOMAINS[index]
    return "%s_%02d" % (BASE_DOMAINS[index % len(BASE_DOMAINS)], index)


# --------------------------------------------------------------------------
# YAML emission helpers
# --------------------------------------------------------------------------

class Doc:
    """Tiny indent-aware YAML writer."""

    def __init__(self) -> None:
        self.lines: List[str] = []

    def raw(self, text: str) -> None:
        self.lines.append(text)

    def key(self, indent: int, key: str, value) -> None:
        self.lines.append("%s%s: %s" % (" " * indent, key, scalar(value)))

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"


def scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[%s]" % ", ".join(scalar(v) for v in value)
    s = str(value)
    # Quote when the value could be read as a non-string YAML scalar.
    if s == "" or _looks_numeric(s) or any(c in s for c in ":#{}[],&*?|-<>=!%@`\""):
        return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')
    return s


def _looks_numeric(s: str) -> bool:
    try:
        float(s)
        return True
    except ValueError:
        return False


def block_string(doc: Doc, indent: int, key: str, body: str) -> None:
    doc.raw("%s%s: |" % (" " * indent, key))
    for line in body.rstrip("\n").split("\n"):
        doc.raw("%s  %s" % (" " * indent, line))


# --------------------------------------------------------------------------
# Fixture builders
# --------------------------------------------------------------------------

def build_dsl(module_count: int, app_name: str, title: str):
    """Build a full-coverage new-style DSL document of a given size.

    Returns ``(yaml_text, declared_counts)`` where the counts are the number of
    units declared in each DSL section (used for throughput metrics).
    """
    c = {
        "modules": 0, "usecases": 0, "queries": 0, "mutations": 0,
        "routes": 0, "pages": 0, "jobs": 0, "entities": 0, "forms": 0,
        "validations": 0, "uploads": 0, "policies": 0, "resources": 0,
        "iot": 0, "vectorStores": 0, "components": 0,
    }
    doc = Doc()
    doc.raw("# Generated by bench/gen_dsl.py -- do not edit by hand.")
    doc.raw("app:")
    doc.key(2, "name", app_name)
    doc.key(2, "title", title)
    doc.key(2, "version", "1.0.0")
    doc.key(2, "database", "postgres")
    doc.key(2, "features", ["auth", "cron", "realtime-sse", "uploads"])
    doc.raw("  auth:")
    doc.key(4, "userEntity", "user")
    doc.key(4, "methods", ["password", "oauth"])
    doc.key(4, "onAuthFailedRedirectTo", "/login")
    doc.raw("")

    domains = [domain_name(i) for i in range(module_count)]

    # ---- modules ---------------------------------------------------------
    doc.raw("modules:")
    for i, dom in enumerate(domains):
        c["modules"] += 1
        p = pascal(dom)
        doc.raw("  %s:" % dom)
        doc.raw("    entity:")
        doc.raw("      fields:")
        for fname, ftype in ENTITY_FIELDS:
            doc.key(8, fname, ftype)
        doc.raw("    usecases:")
        # Three usecases per module, each with a distinct input surface.
        specs = [
            ("create%s" % p, UC_INPUT_POOL[:3], p),
            ("get%s" % p, UC_INPUT_POOL[:1], p),
            ("list%ss" % p, UC_INPUT_POOL[4:6], "Vec<%s>" % p),
        ]
        for uc_name, inputs, output in specs:
            doc.raw("      %s:" % uc_name)
            doc.raw("        input:")
            for fname, ftype in inputs:
                doc.key(10, fname, ftype)
            doc.key(8, "output", output)
            doc.key(8, "doc", "Generated usecase for %s" % dom)
            # `steps` become graph edges; the only always-present node is the
            # module's own entity, whose id equals the module name.
            doc.key(8, "steps", [dom])
            c["usecases"] += 1
    doc.raw("")

    # ---- queries ---------------------------------------------------------
    doc.raw("queries:")
    for i, dom in enumerate(domains):
        p = pascal(dom)
        doc.raw("  - name: list%ss" % p)
        doc.key(4, "handler", "./backend/queries/list_%s.rs" % dom)
        doc.key(4, "entities", [p])
        doc.raw("    cache:")
        doc.key(6, "ttl", 60)
        doc.key(6, "key", "%s:list" % dom)
        doc.raw("  - name: get%sById" % p)
        doc.key(4, "handler", "./backend/queries/get_%s_by_id.rs" % dom)
        doc.key(4, "entities", [p])
        c["queries"] += 2
    doc.raw("")

    # ---- mutations -------------------------------------------------------
    doc.raw("mutations:")
    for i, dom in enumerate(domains):
        p = pascal(dom)
        doc.raw("  - name: create%s" % p)
        doc.key(4, "handler", "./backend/mutations/create_%s.rs" % dom)
        doc.key(4, "entities", [p])
        doc.key(4, "authRequired", True)
        doc.key(4, "policy", "isAuthenticated")
        doc.raw("  - name: update%s" % p)
        doc.key(4, "handler", "./backend/mutations/update_%s.rs" % dom)
        doc.key(4, "entities", [p])
        doc.key(4, "authRequired", True)
        doc.key(4, "policy", "isOwner" if i % 2 else "isAdmin")
        c["mutations"] += 2
    doc.raw("")

    # ---- routes & pages --------------------------------------------------
    doc.raw("routes:")
    for i, dom in enumerate(domains):
        p = pascal(dom)
        doc.raw("  - name: %s" % dom)
        doc.key(4, "path", "/%s" % dom)
        doc.key(4, "to", "%sPage" % p)
        doc.key(4, "authRequired", i % 3 == 0)
        doc.key(4, "policy", "isAuthenticated" if i % 3 == 0 else "isPublic")
        c["routes"] += 1
    doc.raw("")
    doc.raw("pages:")
    for i, dom in enumerate(domains):
        doc.raw("  - name: %sPage" % pascal(dom))
        doc.key(4, "component", "%sPage.tsx" % pascal(dom))
        c["pages"] += 1
    doc.raw("")

    # ---- jobs ------------------------------------------------------------
    doc.raw("jobs:")
    for i, dom in enumerate(domains):
        if i % 4:
            continue
        doc.raw("  - name: %s_sync" % dom)
        doc.key(4, "schedule", "0 2 * * *")
        doc.key(4, "handler", "%s.sync" % dom)
        doc.key(4, "policy", "isAdmin")
        c["jobs"] += 1
    doc.raw("")

    # ---- standalone entities (one derive chain root + one per module) -----
    doc.raw("entities:")
    doc.raw("  - name: BaseAudit")
    c["entities"] += 1
    doc.raw("    fields:")
    for fname, ftype in [("id", "uuid"), ("occurredAt", "timestamp"), ("actorId", "uuid")]:
        doc.key(6, fname, ftype)
    for dom in domains:
        p = pascal(dom)
        doc.raw("  - name: %sAudit" % p)
        doc.key(4, "deriveFrom", "BaseAudit")
        doc.raw("    fields:")
        for fname, ftype in [("entityId", "uuid"), ("action", "string"), ("payload", "string")]:
            doc.key(6, fname, ftype)
        c["entities"] += 1
    doc.raw("")

    # ---- forms -----------------------------------------------------------
    doc.raw("forms:")
    for i, dom in enumerate(domains):
        p = pascal(dom)
        doc.raw("  - name: %sForm" % p)
        doc.key(4, "submitTo", "create%s" % p)
        doc.raw("    fields:")
        for fname, ftype in [("name", "string"), ("amount", "float"), ("tenantId", "uuid")]:
            doc.key(6, fname, ftype)
        doc.key(4, "policy", "isAuthenticated")
        c["forms"] += 1
    doc.raw("")

    # ---- validations (must target real <module>.<usecase>.<field> paths) --
    # `appliesTo` must name a real <module>.<usecase>.<input-field> triple or
    # validate_validations rejects the whole document. create<P> takes
    # (id, tenantId, query); list<P>s takes (limit, offset).
    doc.raw("validations:")
    for i, dom in enumerate(domains):
        p = pascal(dom)
        rules = [
            ("create%s" % p, "id", "id must be a valid uuid"),
            ("create%s" % p, "query", "query length must be between 1 and 200"),
            ("list%ss" % p, "limit", "limit must be greater than 0"),
        ]
        for j, (uc, field, rule) in enumerate(rules):
            if j >= 2 and i % 2:
                continue
            doc.raw("  - name: %s%sIsValid" % (dom, field.capitalize()))
            doc.key(4, "appliesTo", "%s.%s.%s" % (dom, uc, field))
            doc.key(4, "rule", rule)
            c["validations"] += 1
    doc.raw("")

    # ---- uploads ---------------------------------------------------------
    doc.raw("uploads:")
    for i, dom in enumerate(domains):
        if i % 8:
            continue
        doc.raw("  - name: %sAsset" % dom)
        doc.key(4, "path", "/uploads/%s" % dom)
        c["uploads"] += 1
    doc.raw("")

    # ---- policies --------------------------------------------------------
    doc.raw("policies:")
    for name, guard in [
        ("isAuthenticated", "check_authenticated"),
        ("isAdmin", "check_admin"),
        ("isOwner", "check_owner"),
        ("isPublic", "always_allow"),
    ]:
        doc.raw("  - name: %s" % name)
        doc.key(4, "guard", guard)
    for i, dom in enumerate(domains):
        if i % 4:
            continue
        doc.raw("  - name: canManage%s" % pascal(dom))
        doc.key(4, "guard", "check_%s" % dom)
        c["policies"] += 1
    doc.raw("")

    # ---- resources -------------------------------------------------------
    doc.raw("resources:")
    doc.raw("  - name: cache")
    doc.key(4, "type", "redis")
    doc.raw("    config:")
    doc.key(6, "url", "redis://localhost:6379")
    for i, dom in enumerate(domains):
        if i % 4:
            continue
        doc.raw("  - name: %sQueue" % dom)
        doc.key(4, "type", "sqs")
        doc.raw("    config:")
        doc.key(6, "queue", "%s-events" % dom)
        c["resources"] += 1
    doc.raw("")

    # ---- iot -------------------------------------------------------------
    doc.raw("iot:")
    for i, dom in enumerate(domains):
        if i % 8:
            continue
        doc.raw("  - name: read%sSensor" % pascal(dom))
        doc.key(4, "protocol", "mqtt")
        doc.key(4, "driver", "rumqttc")
        doc.key(4, "simulate", True)
        block_string(
            doc, 4, "code",
            "pub fn read_%s_sensor() -> f32 {\n    21.5\n}" % dom,
        )
        doc.raw("    expose:")
        doc.key(6, "method", "GET")
        doc.key(6, "path", "/iot/%s/sensor" % dom)
        doc.key(6, "protocol", "http")
        doc.key(6, "generateHook", True)
        doc.key(6, "generateComponent", True)
        c["iot"] += 1
    doc.raw("")

    # ---- vector stores & ai models ---------------------------------------
    doc.raw("vectorStores:")
    for i, dom in enumerate(domains):
        if i % 10:
            continue
        doc.raw("  - name: %sEmbeddings" % dom)
        doc.key(4, "embeddingModel", "text-embedding-3-small")
        doc.key(4, "dimensions", 1536)
        c["vectorStores"] += 1
    doc.raw("")
    doc.raw("aiModels:")
    doc.raw("  - name: supportAssistant")
    doc.key(4, "provider", "openai")
    doc.key(4, "model", "gpt-4o-mini")
    doc.raw("    config:")
    doc.key(6, "temperature", "0.2")
    doc.raw("")

    # ---- shared components ----------------------------------------------
    doc.raw("components:")
    for dom in domains:
        p = pascal(dom)
        doc.raw("  - name: %sCard" % p)
        doc.raw("    props:")
        for fname, ftype in [("title", "string"), ("amount", "float"), ("active", "bool")]:
            doc.raw("      - name: %s" % fname)
            doc.key(8, "type", ftype)
        c["components"] += 1

    c["policies"] += 4  # the four built-in guards declared unconditionally
    return doc.text(), c


def build_collide() -> str:
    """One module declaring many usecases -- probes per-module file collisions."""
    doc = Doc()
    doc.raw("# Collision probe: many usecases inside a single module.")
    doc.raw("app:")
    doc.key(2, "name", "collide")
    doc.key(2, "title", "Collision probe")
    doc.key(2, "database", "postgres")
    doc.raw("modules:")
    doc.raw("  order:")
    doc.raw("    entity:")
    doc.raw("      fields:")
    for fname, ftype in [("code", "string"), ("amount", "float")]:
        doc.key(8, fname, ftype)
    doc.raw("    usecases:")
    for verb in ["create", "update", "cancel", "refund", "ship", "archive"]:
        doc.raw("      %sOrder:" % verb)
        doc.raw("        input:")
        doc.key(10, "id", "uuid")
        doc.key(8, "output", "Order")
        doc.key(8, "steps", ["order"])
    return doc.text()


def build_legacy_graph() -> str:
    """Legacy raw node graph: ports, adapters, entity, usecases."""
    doc = Doc()
    doc.raw("# Legacy raw-graph fixture: ports, adapters and explicit entities.")
    doc.key(0, "module", "billing")
    doc.raw("nodes:")
    doc.raw("  - id: invoiceReaderPort")
    doc.key(4, "type", "port")
    doc.raw("  - id: invoiceWriterPort")
    doc.key(4, "type", "port")
    doc.raw("  - id: invoiceRepository")
    doc.key(4, "type", "adapter")
    doc.key(4, "implements", "invoiceReaderPort")
    doc.raw("  - id: invoice")
    doc.key(4, "type", "entity")
    doc.raw("    input:")
    for fname, ftype in [("id", "uuid"), ("number", "string"), ("total", "float"),
                         ("issuedAt", "timestamp"), ("paid", "bool")]:
        doc.raw("      - name: %s" % fname)
        doc.key(8, "type", ftype)
    for uc, out in [("createInvoice", "Invoice"), ("getInvoice", "Invoice"),
                    ("listInvoices", "Vec<Invoice>"), ("voidInvoice", "Invoice")]:
        doc.raw("  - id: %s" % uc)
        doc.key(4, "type", "usecase")
        doc.raw("    input:")
        doc.raw("      - name: id")
        doc.key(8, "type", "uuid")
        doc.key(4, "output", out)
        doc.key(4, "depends_on", ["invoiceRepository"])
        doc.key(4, "doc", "Billing usecase %s" % uc)
    return doc.text()


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

TIERS: Dict[str, int] = {"tier1": 2, "tier2": 8, "tier3": 20, "tier4": 40, "tier5": 100}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="bench/dsl", help="output directory for fixtures")
    ap.add_argument("--only", default=None, help="generate only this fixture")
    args = ap.parse_args()

    out = args.out
    os.makedirs(out, exist_ok=True)
    written: List[str] = []

    def emit(name: str, content: str) -> None:
        if args.only and args.only != name:
            return
        path = os.path.join(out, name + ".yaml")
        with open(path, "w") as fh:
            fh.write(content)
        written.append(path)

    for tier, count in TIERS.items():
        emit(tier, build_dsl(count, tier, "Benchmark %s" % tier)[0])
    emit("atlas", build_dsl(14, "atlas", "Atlas Commerce Platform")[0])
    emit("collide", build_collide())
    emit("legacy_graph", build_legacy_graph())

    for path in written:
        size = os.path.getsize(path)
        print("wrote %-28s %7d bytes" % (path, size))


if __name__ == "__main__":
    main()
