/*
 Generated by typeshare 1.13.3
*/


export interface DslAuth {
	userEntity: string;
	methods?: string[];
	onAuthFailedRedirectTo?: string;
}

export interface DslApp {
	name: string;
	title?: string;
	version?: string;
	database?: string;
	features?: string[];
	auth?: DslAuth;
}

export interface DslAppPage {
	name: string;
	component: string;
}

export interface DslCache {
	ttl: number;
	key: string;
}

export interface DslEntity {
	deriveFrom?: string;
	fields?: BTreeMap<string, string>;
}

export interface DslForm {
	fields?: string[];
	action: string;
}

export interface DslIotExpose {
	method?: string;
	path?: string;
	protocol?: string;
	generateHook?: boolean;
	generateComponent?: boolean;
}

export interface DslIot {
	name: string;
	code: string;
	protocol?: string;
	driver?: string;
	simulate?: boolean;
	expose?: DslIotExpose;
}

export interface DslJob {
	name: string;
	schedule: string;
	handler: string;
	policy?: string;
}

export interface DslModule {
	entity?: DslEntity;
	usecases?: BTreeMap<string, DslUseCase>;
	pages?: BTreeMap<string, DslPage>;
	rpc?: BTreeMap<string, DslUseCase>;
}

export interface DslMutation {
	name: string;
	handler: string;
	entities?: string[];
	authRequired?: boolean;
	policy?: string;
}

export interface DslPage {
	route: string;
	component?: string;
	form?: DslForm;
}

export interface DslPolicy {
	name: string;
	guard: string;
}

export interface DslQuery {
	name: string;
	handler: string;
	entities?: string[];
	cache?: DslCache;
}

export interface DslResource {
	name: string;
	type: string;
	config?: BTreeMap<string, string>;
}

export interface DslRoute {
	name: string;
	path: string;
	to: string;
	authRequired?: boolean;
	policy?: string;
}

export interface DslStandaloneEntity {
	name: string;
	deriveFrom?: string;
	fields?: BTreeMap<string, string>;
}

export interface DslStandaloneForm {
	name: string;
	submitTo: string;
	fields?: BTreeMap<string, string>;
	policy?: string;
}

export interface DslUpload {
	name: string;
	path?: string;
}

export interface DslUseCase {
	input?: BTreeMap<string, string>;
	output?: string;
	doc?: string;
	steps?: DslStep[];
}

export interface DslValidation {
	name: string;
	appliesTo: string;
	rule: string;
}

export interface Field {
	name: string;
	type: string;
}

export interface SharedComponent {
	name: string;
	props?: Field[];
}

export interface FerrumDsl {
	app: DslApp;
	modules?: BTreeMap<string, DslModule>;
	routes?: DslRoute[];
	pages?: DslAppPage[];
	components?: SharedComponent[];
	queries?: DslQuery[];
	mutations?: DslMutation[];
	jobs?: DslJob[];
	entities?: DslStandaloneEntity[];
	forms?: DslStandaloneForm[];
	validations?: DslValidation[];
	uploads?: DslUpload[];
	policies?: DslPolicy[];
	resources?: DslResource[];
	iot?: DslIot[];
}

export enum NodeType {
	UseCase = "usecase",
	Adapter = "adapter",
	Port = "port",
	Entity = "entity",
	Component = "component",
	Hook = "hook",
	Schema = "schema",
	Form = "form",
	Validation = "validation",
	Upload = "upload",
	Policy = "policy",
	Resource = "resource",
}

export interface Node {
	id: string;
	type: NodeType;
	doc?: string;
	description?: string;
	story?: string;
	input?: Field[];
	output?: string;
	depends_on?: string[];
	implements?: string;
	view?: string;
	schema?: string;
	api_name?: string;
	ref?: string;
}

export interface Module {
	module: string;
	nodes: Node[];
}

