/**
 * Shared Types Index
 * 
 * Central export point for all shared type definitions used throughout
 * the Semantic Code Graph application.
 */

// API Response Types
export * from './api-responses';

// Utility Types - Export specific items to avoid conflicts
export type {
  NonEmptyArray,
  MinLengthArray,
  MaxLengthArray,
  FixedLengthArray,
  RequiredKeys,
  OptionalKeys,
  DeepPartial,
  DeepRequired,
  DeepReadonly,
  Nullable,
  Optional,
  Maybe,
  NonNullable,
  NonEmptyString,
  EmailString,
  UrlString,
  UuidString,
  IsoDateString,
  FilePathString,
  AsyncFunction,
  EventHandler,
  Callback,
  Predicate,
  Mapper,
  Reducer,
  Result,
  Success,
  Failure,
  Option,
  Some,
  None,
  HttpMethod,
  HttpStatusCode,
  ContentType,
  RequestHeaders,
  ValidationResult,
  ValidationError,
  Validator,
  LoadingState,
  AsyncState,
  PaginationState,
  SortState,
  FilterState,
  BaseComponentProps,
  WithChildren,
  WithOptionalChildren,
  RefForwardingComponent,
  CustomEvent,
  EventEmitter,
  Environment,
  LogLevel,
  Config,
  Brand,
  ProjectId,
  UserId,
  TemplateId,
  NodeId,
  EdgeId,
  Timestamp,
  IsoTimestamp,
  Percentage,
  Score,
  Confidence,
  KeysOfType,
  PropertiesOfType,
  ExcludePropertiesOfType,
  OptionalPropertiesOfType,
  RequiredPropertiesOfType,
} from './utility-types';

export {
  isNotNull,
  isNotUndefined,
  isNotNullable,
  isNonEmptyString as utilityIsNonEmptyString,
  isNonEmptyArray,
  isObject as utilityIsObject,
  isFunction,
  isPromise,
} from './utility-types';

// Type Guards - Export specific items to avoid conflicts
export {
  isObject as typeGuardIsObject,
  isNonEmptyString as typeGuardIsNonEmptyString,
  isValidNumber,
  isArray,
  isDateString,
  isApiResponse,
  isGraphNode,
  isGraphEdge,
  isTemplate,
  isProject,
  isKthuluCommand,
  isValidationResult,
  isMetricValue,
  isAlertData,
  validateApiResponse,
  validateArray,
  safeJsonParse,
  typedFetch,
  typedApiResponseFetch,
} from './type-guards';

// Framework-Specific Types - Export specific types to avoid conflicts
export type {
  FerrumGraphData,
  FerrumDSL,
  FerrumGraphNode,
  FerrumGraphEdge,
  FerrumNodeData,
  FerrumApp,
  FerrumEntity,
  FerrumUseCase,
  FerrumAdapter,
  FerrumPort,
  FerrumModule,
  FerrumIoTComponent,
  FerrumValidationResult,
  Position,
} from './ferrum-types';

export {
  FerrumGraphDataSchema,
  FerrumDSLSchema,
  FerrumGraphNodeSchema,
  FerrumGraphEdgeSchema,
  FerrumNodeDataSchema,
  PositionSchema,
  isFerrumGraphData,
  isFerrumDSL,
  validateFerrumGraphData,
  validateFerrumDSL,
  serializeFerrumGraphData,
  deserializeFerrumGraphData,
  serializeFerrumDSL,
  deserializeFerrumDSL,
} from './ferrum-types';