//! Ownership markers for generated files.
//!
//! Every file `ferrum compile` fully derives from the graph or the templates
//! starts with a generated-code header, for example
//!
//! ```text
//! // Code generated by ferrum. DO NOT EDIT.
//! ```
//!
//! (with `#`, `--` or `<!-- -->` instead of `//` where the file type needs it).
//! Tools such as vord read this header and refuse hand edits to the file.
//!
//! The places where a person or an agent is expected to write logic are
//! *holes*: named regions delimited by marker lines.
//!
//! ```text
//!     // vord:hole mutation-create-user
//!     // ⛳ AI_FILL[mutation_logic] --context=mutation:createUser
//!     Json(_input)
//!     // vord:end-hole
//! ```
//!
//! Everything outside a hole, including the marker lines, belongs to the
//! generator. When ferrum rewrites a file that already exists, the body of
//! each hole is carried over by name, so recompiling never discards
//! hand-written logic.
//!
//! Files that ferrum only creates once and then hands over (placeholder pages,
//! `custom.rs`, the `ferrum init` scaffold, ...) carry neither a header nor
//! holes: they are entirely user-owned.

use anyhow::{Context, Result};
use inflector::Inflector;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

/// Text of the generated-code header, without comment syntax.
pub const GENERATED_NOTICE: &str = "Code generated by ferrum. DO NOT EDIT.";

/// Prefix of the line that opens a hole; the hole's name follows it.
pub const HOLE_START: &str = "vord:hole";

/// Text of the line that closes a hole.
pub const HOLE_END: &str = "vord:end-hole";

/// How many leading lines are searched for the generated-code header.
pub const HEADER_SCAN_LINES: usize = 10;

/// Regex (for the `regex` crate) matching the canonical AI_FILL marker
/// `// ⛳ AI_FILL[task] --context=kind:id` that sits inside holes.
///
/// It also accepts the older spellings `⛳️` (with a variation selector),
/// `⚙` and `--context NODE` so files produced by earlier versions still
/// match.
pub const AI_FILL_PATTERN: &str = r"//\s*(?:\x{26F3}\x{FE0F}?|\x{2699}\x{FE0F}?)\s*AI_FILL\[(?P<task>[^\]]+)\]\s*--context[= ](?P<context>[^\n]+)";

/// Comment syntax used for marker lines in a given file type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommentStyle {
    /// A line comment such as `//`, `#` or `--`.
    Line(&'static str),
    /// A block comment such as `<!-- ... -->` or `/* ... */`.
    Block(&'static str, &'static str),
}

impl CommentStyle {
    /// Comment syntax for `path`, or `None` when the format has no comments
    /// (JSON) or is unknown, in which case no header is written.
    pub fn for_path(path: &Path) -> Option<Self> {
        let name = path.file_name()?.to_str()?;
        if name == "Dockerfile" || name == "Makefile" || name.starts_with(".env") {
            return Some(Self::Line("#"));
        }
        let ext = path.extension()?.to_str()?.to_ascii_lowercase();
        Some(match ext.as_str() {
            "rs" | "ts" | "tsx" | "js" | "jsx" | "mjs" | "cjs" | "go" | "c" | "h" | "cpp"
            | "java" | "kt" | "swift" | "proto" | "graphql" => Self::Line("//"),
            "toml" | "yaml" | "yml" | "py" | "sh" | "rb" | "ini" | "cfg" => Self::Line("#"),
            "sql" => Self::Line("--"),
            "md" | "html" | "htm" | "xml" | "svg" | "vue" => Self::Block("<!--", "-->"),
            "css" | "scss" => Self::Block("/*", "*/"),
            _ => return None,
        })
    }

    /// Wrap `text` in this comment syntax.
    pub fn comment(&self, text: &str) -> String {
        match self {
            Self::Line(prefix) => format!("{prefix} {text}"),
            Self::Block(open, close) => format!("{open} {text} {close}"),
        }
    }
}

/// The header line for files using `style`.
pub fn header_line(style: CommentStyle) -> String {
    style.comment(GENERATED_NOTICE)
}

/// Whether `content` already carries a generated-code header in its first
/// [`HEADER_SCAN_LINES`] lines (the same rule vord applies).
pub fn has_generated_header(content: &str) -> bool {
    content.lines().take(HEADER_SCAN_LINES).any(|line| {
        (line.contains("Code generated") && line.contains("DO NOT EDIT"))
            || line.contains("@generated")
    })
}

/// Prepend the generated-code header to `content` unless it is already
/// there or the file type has no comment syntax.
pub fn with_header(path: &Path, content: &str) -> String {
    let Some(style) = CommentStyle::for_path(path) else {
        return content.to_string();
    };
    if has_generated_header(content) {
        return content.to_string();
    }
    let header = header_line(style);
    // Keep a shebang on the first line where it has to be.
    if content.starts_with("#!") {
        let (first, rest) = content.split_once('\n').unwrap_or((content, ""));
        return format!("{first}\n{header}\n{rest}");
    }
    format!("{header}\n{content}")
}

/// Canonical hole name: `<kind>-<id in kebab-case>`, e.g.
/// `hole_name("mutation", "createUser") == "mutation-create-user"`.
pub fn hole_name(kind: &str, id: &str) -> String {
    let raw = format!("{kind}-{}", id.to_kebab_case());
    let mut name = String::with_capacity(raw.len());
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' {
            name.push(c.to_ascii_lowercase());
        } else if !name.ends_with('-') {
            name.push('-');
        }
    }
    name.trim_matches('-').to_string()
}

/// The canonical AI_FILL marker text (without comment syntax).
pub fn ai_fill(task: &str, context: &str) -> String {
    format!("\u{26F3} AI_FILL[{task}] --context={context}")
}

/// A hole written with `//` line comments, indented by `indent`.
///
/// The hole holds the AI_FILL marker for `task`/`context` followed by
/// `placeholder` (each of its lines indented), which is what compiles until
/// someone fills the hole in. The result ends with a newline.
pub fn line_hole(indent: &str, name: &str, task: &str, context: &str, placeholder: &str) -> String {
    let mut out = format!("{indent}// {HOLE_START} {name}\n");
    out.push_str(&format!("{indent}// {}\n", ai_fill(task, context)));
    for line in placeholder.lines() {
        if line.trim().is_empty() {
            out.push('\n');
        } else {
            out.push_str(&format!("{indent}{line}\n"));
        }
    }
    out.push_str(&format!("{indent}// {HOLE_END}\n"));
    out
}

/// Name of the hole opened on `line`, if it opens one.
fn hole_start_name(line: &str) -> Option<String> {
    let idx = line.find(HOLE_START)?;
    let rest = &line[idx + HOLE_START.len()..];
    // `vord:hole` must be followed by whitespace and a name.
    if !rest.starts_with(char::is_whitespace) {
        return None;
    }
    let name: String = rest
        .trim_start()
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
        .collect();
    (!name.is_empty()).then_some(name)
}

fn is_hole_end(line: &str) -> bool {
    line.contains(HOLE_END)
}

/// A hole found in a file: its name and the line range of its body
/// (exclusive of both marker lines).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Hole {
    pub name: String,
    pub body: std::ops::Range<usize>,
}

/// Every well-formed hole in `lines`, in order. A start marker without a
/// matching end marker is ignored.
pub fn find_holes<S: AsRef<str>>(lines: &[S]) -> Vec<Hole> {
    let mut holes = Vec::new();
    let mut open: Option<(String, usize)> = None;
    for (index, line) in lines.iter().enumerate() {
        let line = line.as_ref();
        if is_hole_end(line) {
            if let Some((name, start)) = open.take() {
                holes.push(Hole {
                    name,
                    body: start + 1..index,
                });
            }
        } else if let Some(name) = hole_start_name(line) {
            open = Some((name, index));
        }
    }
    holes
}

/// Hole bodies of `content`, by name. When a name repeats, the first wins.
pub fn hole_bodies(content: &str) -> HashMap<String, Vec<String>> {
    let lines: Vec<&str> = content.lines().collect();
    let mut bodies = HashMap::new();
    for hole in find_holes(&lines) {
        bodies
            .entry(hole.name)
            .or_insert_with(|| lines[hole.body].iter().map(|l| l.to_string()).collect());
    }
    bodies
}

/// Result of merging a freshly rendered file with the one on disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Merged {
    /// The file to write.
    pub content: String,
    /// Names of the kept holes that the fresh render no longer has, sorted.
    /// Their content could not be carried over.
    pub orphaned: Vec<String>,
    /// Bodies of the `orphaned` holes, by name.
    pub leftover: HashMap<String, Vec<String>>,
}

/// Carry each hole body of `existing` over into the hole with the same name
/// in `fresh`. Everything outside holes comes from `fresh`.
pub fn merge_holes(existing: &str, fresh: &str) -> Merged {
    merge_hole_bodies(hole_bodies(existing), fresh)
}

/// Like [`merge_holes`], with the kept hole bodies given directly.
pub fn merge_hole_bodies(mut kept: HashMap<String, Vec<String>>, fresh: &str) -> Merged {
    let fresh_lines: Vec<&str> = fresh.lines().collect();
    let holes = find_holes(&fresh_lines);

    let mut out: Vec<String> = Vec::with_capacity(fresh_lines.len());
    let mut cursor = 0;
    for hole in &holes {
        out.extend(
            fresh_lines[cursor..hole.body.start]
                .iter()
                .map(|l| l.to_string()),
        );
        match kept.remove(&hole.name) {
            Some(body) => out.extend(body),
            None => out.extend(fresh_lines[hole.body.clone()].iter().map(|l| l.to_string())),
        }
        cursor = hole.body.end;
    }
    out.extend(fresh_lines[cursor..].iter().map(|l| l.to_string()));

    let mut content = out.join("\n");
    if fresh.ends_with('\n') || fresh.is_empty() {
        content.push('\n');
    }
    let mut orphaned: Vec<String> = kept.keys().cloned().collect();
    orphaned.sort();
    Merged {
        content,
        orphaned,
        leftover: kept,
    }
}

/// Render the final content of a generated file: the header is added and,
/// when the file already exists, hole bodies are carried over by name.
pub fn render_generated(path: &Path, existing: Option<&str>, fresh: &str) -> Merged {
    let fresh = with_header(path, fresh);
    match existing {
        Some(existing) => merge_holes(existing, &fresh),
        None => Merged {
            content: fresh,
            orphaned: Vec::new(),
            leftover: HashMap::new(),
        },
    }
}

type HoleMap = HashMap<String, Vec<String>>;

#[derive(Default)]
struct Stash {
    /// Hole bodies that a write could not place, by file. Several generators
    /// write the same file more than once in one run (for example one
    /// handler file per module, rendered once per use case), so a hole
    /// missing from one render may come back in the next; it waits here.
    parked: HashMap<PathBuf, HoleMap>,
    /// The bodies ferrum itself rendered for each hole, by file, so parked
    /// holes that only hold that default are not reported as lost work.
    rendered: HashMap<PathBuf, HoleMap>,
}

fn stash() -> std::sync::MutexGuard<'static, Stash> {
    static STASH: OnceLock<Mutex<Stash>> = OnceLock::new();
    STASH
        .get_or_init(Default::default)
        .lock()
        .unwrap_or_else(|e| e.into_inner())
}

/// Holes with edited content under `root` that no render of their file has
/// written back since the last call, as `(file, hole name)`. Clears the
/// record for `root`.
///
/// Call it once a compile has finished to tell the user about hand-written
/// content that no longer has a place (typically after renaming a node).
pub fn take_orphaned_holes(root: &Path) -> Vec<(PathBuf, String)> {
    let mut stash = stash();
    let rendered: HashMap<PathBuf, HoleMap> = stash
        .rendered
        .extract_if(|path, _| path.starts_with(root))
        .collect();
    let parked: Vec<(PathBuf, HoleMap)> = stash
        .parked
        .extract_if(|path, _| path.starts_with(root))
        .collect();
    let mut orphans: Vec<(PathBuf, String)> = parked
        .into_iter()
        .flat_map(|(path, holes)| {
            let defaults = rendered.get(&path).cloned().unwrap_or_default();
            holes
                .into_iter()
                .filter(move |(name, body)| defaults.get(name) != Some(body))
                .map(move |(name, _)| (path.clone(), name))
        })
        .collect();
    orphans.sort();
    orphans
}

/// Write a generated file: header added, hole bodies of the current file kept.
///
/// Holes the new render does not have are parked (see
/// [`take_orphaned_holes`]) so that a later render of the same file in this
/// run can still pick them up.
pub fn write_generated<P: AsRef<Path>>(path: P, content: &str) -> Result<()> {
    let path = path.as_ref();
    let fresh = with_header(path, content);
    let mut kept = fs::read_to_string(path)
        .map(|existing| hole_bodies(&existing))
        .unwrap_or_default();
    let merged = {
        let mut stash = stash();
        if let Some(parked) = stash.parked.remove(path) {
            for (name, body) in parked {
                kept.entry(name).or_insert(body);
            }
        }
        stash
            .rendered
            .entry(path.to_path_buf())
            .or_default()
            .extend(hole_bodies(&fresh));
        let mut merged = merge_hole_bodies(kept, &fresh);
        if !merged.leftover.is_empty() {
            stash
                .parked
                .insert(path.to_path_buf(), std::mem::take(&mut merged.leftover));
        }
        merged
    };
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
    }
    fs::write(path, merged.content)
        .with_context(|| format!("Failed to write file: {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn header_uses_file_comment_syntax() {
        assert_eq!(
            with_header(&PathBuf::from("a.rs"), "fn a() {}\n"),
            "// Code generated by ferrum. DO NOT EDIT.\nfn a() {}\n"
        );
        assert!(with_header(&PathBuf::from("Cargo.toml"), "")
            .starts_with("# Code generated by ferrum. DO NOT EDIT."));
        assert!(with_header(&PathBuf::from("up.sql"), "")
            .starts_with("-- Code generated by ferrum. DO NOT EDIT."));
        assert!(with_header(&PathBuf::from("doc.md"), "")
            .starts_with("<!-- Code generated by ferrum. DO NOT EDIT. -->"));
        // JSON has no comments: left untouched.
        assert_eq!(with_header(&PathBuf::from("a.json"), "{}"), "{}");
    }

    #[test]
    fn header_is_idempotent() {
        let once = with_header(&PathBuf::from("a.ts"), "export {}\n");
        assert_eq!(with_header(&PathBuf::from("a.ts"), &once), once);
    }

    #[test]
    fn hole_names_are_kebab_case() {
        assert_eq!(hole_name("mutation", "createUser"), "mutation-create-user");
        assert_eq!(hole_name("iot", "Blink"), "iot-blink");
        assert_eq!(hole_name("query", "get_posts"), "query-get-posts");
    }

    #[test]
    fn line_hole_wraps_ai_fill_and_placeholder() {
        let hole = line_hole("    ", "job-cleanup", "job_logic", "job:Cleanup", "");
        assert_eq!(
            hole,
            "    // vord:hole job-cleanup\n    // \u{26F3} AI_FILL[job_logic] --context=job:Cleanup\n    // vord:end-hole\n"
        );
    }

    #[test]
    fn merge_keeps_hole_bodies_by_name() {
        let old = "// head v1\n// vord:hole a\nmine_a();\n// vord:end-hole\n// vord:hole b\nmine_b();\n// vord:end-hole\n";
        let new = "// head v2\n// vord:hole b\nstub_b();\n// vord:end-hole\n// vord:hole a\nstub_a();\n// vord:end-hole\n// vord:hole c\nstub_c();\n// vord:end-hole\n";
        let merged = merge_holes(old, new);
        assert_eq!(
            merged.content,
            "// head v2\n// vord:hole b\nmine_b();\n// vord:end-hole\n// vord:hole a\nmine_a();\n// vord:end-hole\n// vord:hole c\nstub_c();\n// vord:end-hole\n"
        );
        assert!(merged.orphaned.is_empty());
    }

    #[test]
    fn merge_reports_orphaned_holes() {
        let old = "// vord:hole gone\nx();\n// vord:end-hole\n";
        let merged = merge_holes(old, "fn f() {}\n");
        assert_eq!(merged.content, "fn f() {}\n");
        assert_eq!(merged.orphaned, vec!["gone".to_string()]);
    }

    #[test]
    fn hole_markers_work_in_any_comment_syntax() {
        let content = "{/* vord:hole ui */}\n<b/>\n{/* vord:end-hole */}\n# vord:hole cfg\nx = 1\n# vord:end-hole\n";
        let bodies = hole_bodies(content);
        assert_eq!(bodies["ui"], vec!["<b/>".to_string()]);
        assert_eq!(bodies["cfg"], vec!["x = 1".to_string()]);
    }

    #[test]
    fn end_marker_is_not_a_start_marker() {
        assert_eq!(hole_start_name("// vord:end-hole"), None);
        assert_eq!(hole_start_name("// vord:holey"), None);
        assert_eq!(hole_start_name("// vord:hole x-1 */"), Some("x-1".into()));
    }
}
